// <auto-generated />
using DotNetReact_BackEnd.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DotNetReact_BackEnd.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20220914160657_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_general_ci")
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");

            modelBuilder.Entity("DotNetReact_BackEnd.Models.Strings", b =>
                {
                    b.Property<string>("String")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("string");

                    b.HasKey("String");

                    b.ToTable("strings", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
